name: binance_api
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  convert: ^3.0.0
  crypto: ^3.0.0
  equatable: ^2.0.0
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.5.1
  lint: ^1.5.3

scripts: derry.yaml

import_sorter:
  comments: false
